server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.format_sql: true # 형식화된 sql 문을 보여준다. Beautifier 기능이라고 생각하면 된다
      hibernate.enable_lazy_load_no_trans: true #Lazy Load 를 적용하기 위한 설정
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      connection-timeout: 3000
      maximumPoolSize: 250
      max-lifetime : 30000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simple_board_msa?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234