server:
#  유레카 서버 수신 포트
  port: 8070
eureka:
  instance:
#    유레카 인스턴스 호스트 네임
    hostname: eurekaserver
  client:
#    컨피그 서버가 유레카 서비스에 등록되지 않도록 지시
    registerWithEureka: false
#    컨피그 서버가 캐시 레지스트리 정보를 로컬에 캐시하지 않도록 지시
    fetchRegistry: false
#    서비스 url
    serviceUrl:
      defaultZone:
        http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
#      서버가 요청을 받기 전 초기 대기 시간 설정
      waitTimeInMsWhenSyncEmpty: