server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:
        http://localhost:8070/eureka/
spring:
  cloud:
    gateway:
#      서비스 디스커버리에 등록된 서비스를 기반으로 게이트웨이가 경로를 생성하도록 설정
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
#    슬루스가 Micrometer Tracing으로 바뀜으로 인해 검사하지 않도록 추가 
#    나중에 Micrometer Tracing 학습 필요
    compatibility-verifier:
      enabled: false
#  키클록 관련
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/simple-board-realm
        registration:
          keycloak:
            client-id: simple-board
            client-secret: cdf888b2-1360-4156-87f2-92ae8fe31429
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/keycloak'

management:
  endpoints:
    web:
      exposure:
        include: gateway,refresh
  endpoint:
    gateway:
      enabled: true

keycloak:
  realm: simple-board-realm
  # realm: realm 이름
  resource: simple-board
  # resource: client 이름
  auth-server-url: http://localhost:8080/
  # auth-server-url: http://설정한 키클록url:port/