spring:
  application:
    name: config-server
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

server:
  port: 8071

#암호화 관련
#엔드포인트 /encrypt로 암호화하고 싶은 데이터를 보내면 암호화해서 리턴함
#암호화된 데이터를 "{chiper}암호화 데이터" 식으로 입력한다
encrypt:
  key: my-secret # 사용할 암호
  
# 헤당 설정을 안해놓으면 복호화된 데이터를 리턴하기 때문에 실무에선 설정 후
# 클라이언트 환경변수에 ENCRYPT_KEY=시크릿키 형식으로 넣어 클라이언트에서 복호화 해서 사용하도록 해야한다
#  enabled: false

